<?php require_once('include/header.php'); ?>

<div class="container">
    <div class="breadcrumb breadcrumb-wrap">
        <ul itemscope itemtype="http://schema.org/BreadcrumbList">
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a title="Home" itemprop="item" href="<?php echo $base_url; ?>">
                    <span itemprop="name">Home</span>
                </a>
                <meta itemprop="position" content="1" />
            </li>
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a title="Disclaimer" itemprop="item" href="javascript:void(0)" class="current">
                    <span itemprop="name">Disclaimer</span>
                </a>
                <meta itemprop="position" content="2" />
            </li>
        </ul>
    </div>
</div>
<div class="sub-page">
    <div class="container">
        <div class="row">
            <div class="md-12">
                <h1 class="h2-title" itemprop="headline">Disclaimer</h1>
                <div class="desc-text">
                    <p>Credit card number generated from our website are 100% valid but it does not work like an actual credit card. Only credit card number is valid other details are randomly generated. The credit card details generated by our website are for data testing and verification purposes only. This will help you to not expose your financial credit card details using your real credit card.</p>
                    <p>The information contained in this website is for general information purposes only. The information is provided by Credit Card Generator and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>
                    <p>Credit card number generated from our website are 100% valid but it does not work like an actual credit card. Only credit card number is valid other details are randomly generated. The credit card details generated by our website are for data testing and verification purposes only. This will help you to not expose your financial credit card details using your real credit card.</p>
                    <p>The information contained in this website is for general information purposes only. The information is provided by Credit Card Generator and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.</p>
                </div>
            </div>
        </div>    
    </div>
</div>

<?php require_once('include/footer.php'); ?>